### ISSUE TITLE
Error: Element FunctionImport, unexpected attribute: IsComposable

### ISSUE THREAD

**Issue by richardwang2000** [oasis-tcs/odata-openapi#202]
Tried to convert SharePoint Odata metadata to OpenAPI. The following error shows up.

/usr/local/lib/node_modules/odata-openapi/node_modules/odata-csdl/lib/xml2json.js:1862
    throw enrichedException(e, xml, parser);
    ^

Error: Element FunctionImport, unexpected attribute: IsComposable
    at /usr/local/lib/node_modules/odata-openapi/node_modules/odata-csdl/lib/xml2json.js:1803:15
    at Array.forEach (<anonymous>)
    at setAttributes (/usr/local/lib/node_modules/odata-openapi/node_modules/odata-csdl/lib/xml2json.js:1802:8)
    at SAXParser.parser.onopentag (/usr/local/lib/node_modules/odata-openapi/node_modules/odata-csdl/lib/xml2json.js:633:11)
    at emit (/usr/local/lib/node_modules/odata-openapi/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/odata-openapi/node_modules/sax/lib/sax.js:629:5)
    at openTag (/usr/local/lib/node_modules/odata-openapi/node_modules/sax/lib/sax.js:825:5)
    at SAXParser.write (/usr/local/lib/node_modules/odata-openapi/node_modules/sax/lib/sax.js:1292:13)
    at Object.module.exports.xml2json (/usr/local/lib/node_modules/odata-openapi/node_modules/odata-csdl/lib/xml2json.js:1860:12)
    at convert (/usr/local/lib/node_modules/odata-openapi/lib/cli.js:70:44) {
  parser: {
    construct: '<FunctionImport Name="ComponentContextInfo" ReturnType="Microsoft.SharePoint.Internal.ClientSideComponent.ComponentContextInfo" IsComposable="true" EntitySet="ComponentContextInfos" />',
    line: 3484,
    column: 200
  }
}

**Comment by ralfhandl** [comment]
Hi @richardwang2000, 

could you please provide a copy of the SharePoint `$metadata`?

Thanks in advance
Ralf
