### ISSUE TITLE
Transforming $metadata 4.0 to openapi: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by EfkoNL** [oasis-tcs/odata-openapi#208]
### Problem
When trying to convert a Odata $metadata file to an openapi spec file using the following command:
`odata-openapi -dp response.xml` an error appears with only a partially converted .json file.

### Error message
It only partially transforms the xml and then somewhere stops with the following error:
`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at transformV4 (**<path>**\odata-openapi\tools\transform.js:184:26)
    at transform (**<path>**\odata-openapi\tools\transform.js:125:5)
    at Object.<anonymous> (**<path>**\odata-openapi\tools\transform.js:88:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47`

### Checked
The generated json file indeed has an unexpected ending, it only partially converted the xml file.
Checking the xml file using `java org.apache.xalan.xslt.Process -XSL <path_to_OData-Version.xsl> -IN <path_to_metadata>`
gives 4.0

**Comment by EfkoNL** [comment]
Note: The metadata file im trying to convert is 12451 lines long.

**Comment by ralfhandl** [comment]
Hi @EfkoNL, 

Could you please try that with the newer [pure JavaScript implementation](../tree/main/lib)?

Thanks in advance

**Comment by ralfhandl** [comment]
And of course you can omit the pretty-printing `-p`, then the output will go directly to the file system, without an intermediate string buffer.

With a metadata file of that size you'll probably also want to omit the resource diagram `-d`, that won't be readable anyway, or even lead to a timeout when trying to view the OpenAPI output in Swagger UI or similar.

**Comment by EfkoNL** [comment]
Indeed the newer version did the trick for me, thanks!
