### ISSUE TITLE
Unexpected Token Error

### ISSUE THREAD

**Issue by cnavarro16** [oasis-tcs/odata-openapi#216]
Hi all,

Trying to convert the Northwind XML file to JSON using the csdl2openapi.js script and receive the following error:

```
/Users/cesar/.nvm/versions/node/v12.16.3/lib/node_modules/odata-openapi/lib/csdl2openapi.js:187
                    (overload.$Parameter?.[0].$Collection
                                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/cesar/.nvm/versions/node/v12.16.3/lib/node_modules/odata-openapi/lib/cli.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
```

Any ideas on what I may be doing wrong? I've installed the package globally and am invoking it using the following command:

`odata-openapi3 Northwind-OData4.xml`

**Comment by ralfhandl** [comment]
@cnavarro16 Hi Cesar,

It probably means that you are using Node.js 12 or lower. If that is the case, please switch to a newer version of Node.js. Node 12 reached end-of-life in April 2022.

The `?.` [optional chainging operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is supported since Node.js 14.0.0.

Thanks in advance
Ralf

**Comment by ralfhandl** [comment]
@cnavarro16 with the latest version `odata-openapi@0.18.1` you should now get an error message from `npm` that the minimum node.js requirement isn't met.

**Comment by cnavarro16** [comment]
@ralfhandl Had a look as per your comments and I was, indeed, using Node v12. Once I updated Node the script worked as intended. Thank you!
