### ISSUE TITLE
TypeError: model.element(...).find is not a function

### ISSUE THREAD

**Issue by damithkothalawala** [oasis-tcs/odata-openapi#276]
PATH/odata-openapi/lib/csdl2openapi.js:1521
      .find((overload) => !overload.$IsBound);
       ^

TypeError: model.element(...).find is not a function
    at pathItemActionImport (PATH/odata-openapi/lib/csdl2openapi.js:1521:8)
    at paths (PATH/odata-openapi/lib/csdl2openapi.js:181:9)
    at module.exports.csdl2openapi (PATH/odata-openapi/lib/csdl2openapi.js:84:12)
    at convert (PATH/odata-openapi/lib/cli.js:102:23)
    at Object.<anonymous> (PATH/odata-openapi/lib/cli.js:81:3)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)

Node.js v21.5.0

**Comment by ralfhandl** [comment]
@damithkothalawala Please provide the EDMX input file that causes this error.

Thanks in advance!

**Comment by damithkothalawala** [comment]
[api_meta.txt](https://github.com/oasis-tcs/odata-openapi/files/13947622/api_meta.txt)

Dear @ralfhandl please check attached file.

Thank you for checking on this

**Comment by ralfhandl** [comment]
@damithkothalawala I'll need the OData $metadata file.

Thanks in advance!

**Comment by damithkothalawala** [comment]
Sorry! my bad here is the file 
[Uploading metadata.txt…]()

**Comment by ralfhandl** [comment]
@damithkothalawala Thanks!

Problem is a name collision in the CSDL file: `InstallUpdates` is both the name of an action and the name of a complex type. While one can write that down in XML, it is not allowed, and the action is silently ignored.

I'll prepare a fix later so the tool does not crash and will ignore the action import referencing the ignored action.

Independently of that you can fix the root cause by giving the action a name that does not collide with other schema child elements.

You can keep the name of the action _import_, so changing the action name should not affect clients.
