### ISSUE TITLE
npm install fails on Windows 10

### ISSUE THREAD

**Issue by snebjorn** [oasis-tcs/odata-openapi#34]
I followed the installation instructions. Tried both opt1 and opt2 of node-gyp. Neither made a difference.

I have these set
```
npm config set python python2.7
npm config set msvs_version 2017
```

Log
```
PS C:\Repos\odata-openapi\tools> npm i

> java@0.11.1 install C:\Repos\odata-openapi\tools\node_modules\java
> node-gyp rebuild

C:\Repos\odata-openapi\tools\node_modules\java>if not defined npm_config_node_gyp (node "C:\Users\ME\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\ME\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
  nodeJavaBridge.cpp
c:\repos\odata-openapi\tools\node_modules\nan\nan_converters_43_inl.h(22): warning C4996: 'v8::Value::ToBoolean': was declared deprecated (compiling source file ..\src\java.cpp) [C:\Repos\odata-op
enapi\tools\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\me\.node-gyp\12.4.0\include\node\v8.h(2523): note: see declaration of 'v8::Value::ToBoolean' (compiling source file ..\src\java.cpp)
c:\repos\odata-openapi\tools\node_modules\nan\nan_converters_43_inl.h(22): warning C4996: 'v8::Value::ToBoolean': was declared deprecated (compiling source file ..\src\javaObject.cpp)c:\repos\odat
a-openapi\tools\node_modules\nan\nan_converters_43_inl.h(40): warning C4996: 'v8::Value::BooleanValue': was declared deprecated (compiling source file ..\src\java.cpp) [C:\Repos\odata-openapi\tools\node_modules\java\
build\nodejavabridge_bindings.vcxproj]

  c:\users\me\.node-gyp\12.4.0\include\node\v8.h(2523): note: see declaration of 'v8::Value::ToBoolean' (compiling source file ..\src\javaObject.cpp)c:\users\me\.node-gyp\12.4.0\include\node\v8.h(2561): note: see declaration of 'v8::V
  alue::BooleanValue' (compiling source file ..\src\java.cpp)

c:\repos\odata-openapi\tools\node_modules\nan\nan_converters_43_inl.h(40): warning C4996: 'v8::Value::BooleanValue': was declared deprecated (compiling source file ..\src\javaObject.cpp) [C:\Repos
\odata-openapi\tools\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\me\.node-gyp\12.4.0\include\node\v8.h(2561): note: see declaration of 'v8::Value::BooleanValue' (compiling source file ..\src\javaObject.cpp)
c:\repos\odata-openapi\tools\node_modules\nan\nan_implementation_12_inl.h(103): error C2664: 'v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::Co
nstructorBehavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>' (compiling source file ..\src\java.cpp) [C:\Repos\odata-openapi\tools\node_modules\java\build\nodejav
abridge_bindings.vcxproj]
  c:\repos\odata-openapi\tools\node_modules\nan\nan_implementation_12_inl.h(105): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\src\java.c
  pp)
c:\repos\odata-openapi\tools\node_modules\nan\nan_implementation_12_inl.h(103): error C2664: 'v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::Co
nstructorBehavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>' (compiling source file ..\src\javaObject.cpp) [C:\Repos\odata-openapi\tools\node_modules\java\build\n
odejavabridge_bindings.vcxproj]

A LOT MORE!

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ME\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ME\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ME\Documents\Repos\odata-openapi\tools\node_modules\java
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.11.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ME\AppData\Roaming\npm-cache\_logs\2019-08-13T16_34_44_231Z-debug.log
```

Please help

Node v12.4.0
NPM v6.9.2
JAVA javac 1.8.0_211 (also tried openJDK12)
Python v2.7.16

**Comment by ralfhandl** [comment]
Apparently node-gyp has installation issues with Node 12.

Installation works fine with Node 10.

If your OData service is V4, try the new implementation in https://github.com/oasis-tcs/odata-openapi/tree/master/lib that does not rely on Java and node-gyp.

**Comment by snebjorn** [comment]
Thanks you, that indeed was the problem.

I can recommend https://github.com/coreybutler/nvm-windows for switching node version on windows
