### ISSUE TITLE
Converter does not handle circular references

### ISSUE THREAD

**Issue by jmostella** [oasis-tcs/odata-openapi#90]
Hello,

I ran into this issue when trying to convert the `MSGraph` `OData` metadata to `OpenAPI` format:

```console
Debugger listening on ws://127.0.0.1:42947/d7be1a7a-c259-4d9f-8a96-d9d08ce2f687
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
/tmp/metadata.openapi3.json
console.js:287
Console.prototype.assert = function assert(expression, ...args) {
                                          ^

RangeError: Maximum call stack size exceeded
    at Console.assert (console.js:287:43)
    at nameParts (/home/*******/odata-openapi/lib/csdl2openapi.js:2066:17)
    at Object.keys.filter.forEach.key (/home/*******/odata-openapi/lib/csdl2openapi.js:760:43)
    at Array.forEach (<anonymous>)
    at primitivePaths (/home/*******/odata-openapi/lib/csdl2openapi.js:759:94)
    at Object.keys.filter.forEach.key (/home/*******/odata-openapi/lib/csdl2openapi.js:765:35)
    at Array.forEach (<anonymous>)
    at primitivePaths (/home/*******/odata-openapi/lib/csdl2openapi.js:759:94)
    at Object.keys.filter.forEach.key (/home/*******/odata-openapi/lib/csdl2openapi.js:765:35)
    at Array.forEach (<anonymous>)
Debugger listening on ws://127.0.0.1:42947/d7be1a7a-c259-4d9f-8a96-d9d08ce2f687
For help, see: https://nodejs.org/en/docs/inspector
```

The root cause turns out to be that in the `MSGraph` document there is a circular reference
```xml
<EnumType Name="workbookOperationStatus">
    <Member Name="notStarted" Value="0" />
    <Member Name="running" Value="1" />
    <Member Name="succeeded" Value="2" />
    <Member Name="failed" Value="3" />
</EnumType>
...
<EntityType Name="workbookOperation" BaseType="graph.entity">
    <Property Name="status" Type="graph.workbookOperationStatus" Nullable="false" />
    <Property Name="resourceLocation" Type="Edm.String" />
    <Property Name="error" Type="graph.workbookOperationError" />
</EntityType>
<ComplexType Name="workbookSessionInfo">
    <Property Name="id" Type="Edm.String" />
    <Property Name="persistChanges" Type="Edm.Boolean" />
</ComplexType>
<ComplexType Name="Json" />
<ComplexType Name="workbookOperationError">
    <Property Name="code" Type="Edm.String" />
    <Property Name="message" Type="Edm.String" />
    <Property Name="innerError" Type="graph.workbookOperationError" />
</ComplexType>
```

I have submitted a PR https://github.com/oasis-tcs/odata-openapi/pull/89 that hopefully fixes the issue. Let me know if this is the correct approach.

**Comment by ralfhandl** [comment]
Thanks for finding _and_ fixing this, merged!

**Comment by jmostella** [comment]
no problem!
